defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"

[docker]
domain = "localhost"
endpoint = "unix:///var/run/docker.sock"
exposedByDefault = false
watch = true
